# Bookshop Component: Hero
# Full-width hero section with multiple layout variants

spec:
  structures:
    - content_blocks
  label: Hero
  description: Full-width hero section with heading, subheading, and call-to-action buttons
  icon: view_carousel
  tags:
    - Hero
    - Header

blueprint:
  variant: center
  heading: Your Headline Here
  subheading: A compelling subheading that supports your main message
  background_image:
  background_color: gradient
  overlay_opacity: 60
  buttons: []
  min_height: default

_inputs:
  variant:
    type: select
    label: Layout Variant
    options:
      values:
        - center
        - left
        - right
        - split
    comment: Choose the text alignment and layout style
  heading:
    type: text
    label: Heading
  subheading:
    type: textarea
    label: Subheading
  background_image:
    type: image
    label: Background Image
    comment: Optional background image
  background_color:
    type: select
    label: Background Color
    options:
      values:
        - gradient
        - primary
        - dark
        - light
    comment: Used when no background image is set
  overlay_opacity:
    type: range
    label: Overlay Opacity
    options:
      min: 0
      max: 100
      step: 10
    comment: Darkness of overlay on background image (0-100)
  min_height:
    type: select
    label: Minimum Height
    options:
      values:
        - default
        - tall
        - fullscreen
  buttons:
    type: array
    label: Buttons
    options:
      structures:
        values:
          - value:
              text: Button Text
              url: /
              variant: secondary
            label: Button
            icon: ads_click
            _inputs:
              text:
                type: text
                label: Button Text
              url:
                type: url
                label: URL
              variant:
                type: select
                label: Style
                options:
                  values:
                    - secondary
                    - white
                    - outline
