# Bookshop Component: Pricing
# Pricing table with multiple tiers

spec:
  structures:
    - content_blocks
  label: Pricing
  description: Pricing table with multiple plan options
  icon: payments
  tags:
    - Pricing
    - Plans

blueprint:
  section_title: Simple, Transparent Pricing
  section_description: Choose the plan that works best for you
  background: white
  plans:
    - name: Starter
      price: "$29"
      period: /month
      description: Perfect for getting started
      featured: false
      features:
        - Up to 5 projects
        - Basic analytics
        - Email support
      button_text: Get Started
      button_url: /contact/
    - name: Professional
      price: "$79"
      period: /month
      description: Best for growing businesses
      featured: true
      features:
        - Unlimited projects
        - Advanced analytics
        - Priority support
        - Custom integrations
      button_text: Start Free Trial
      button_url: /contact/
    - name: Enterprise
      price: Custom
      period:
      description: For large organizations
      featured: false
      features:
        - Everything in Pro
        - Dedicated support
        - SLA guarantee
        - Custom development
      button_text: Contact Sales
      button_url: /contact/

_inputs:
  section_title:
    type: text
    label: Section Title
  section_description:
    type: textarea
    label: Section Description
  background:
    type: select
    label: Background
    options:
      values:
        - white
        - light
  plans:
    type: array
    label: Pricing Plans
    options:
      structures:
        values:
          - value:
              name: Plan Name
              price: "$99"
              period: /month
              description: Plan description
              featured: false
              features: []
              button_text: Get Started
              button_url: /contact/
            label: Plan
            icon: payments
            _inputs:
              name:
                type: text
                label: Plan Name
              price:
                type: text
                label: Price
              period:
                type: text
                label: Period
                comment: "e.g., /month, /year"
              description:
                type: text
                label: Description
              featured:
                type: switch
                label: Featured Plan
              features:
                type: array
                label: Features
              button_text:
                type: text
                label: Button Text
              button_url:
                type: url
                label: Button URL
